version: '3.8'

services:
  app_instance_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  app_instance_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  app_instance_3:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5002:5002"  
    environment:
      - PORT=5002

  app_instance_4:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5003:5003"  
    environment:
      - PORT=5003
